version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    #    ignore:
    # Maven plugins
  #      - dependency-name: "org.apache.maven.plugins:maven-assembly-plugin"
  #        versions: "[3.1.1,)"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10  
